/* ─── ELEMENT DATABASE ─── */
const ELEMENTS = {
  H: {
    name: "Hydrogen",
    Z: 1,
    mass: 1.008,
    group: "Nonmetal",
    period: 1,
    ptGroup: 1,
    ptPeriod: 1,
    color: "#2a5a78",
  },
  He: {
    name: "Helium",
    Z: 2,
    mass: 4.003,
    group: "Noble Gas",
    period: 1,
    ptGroup: 18,
    ptPeriod: 1,
    color: "#3a5a80",
  },
  Li: {
    name: "Lithium",
    Z: 3,
    mass: 6.941,
    group: "Alkali Metal",
    period: 2,
    ptGroup: 1,
    ptPeriod: 2,
    color: "#7a3a10",
  },
  Be: {
    name: "Beryllium",
    Z: 4,
    mass: 9.012,
    group: "Alkaline Earth",
    period: 2,
    ptGroup: 2,
    ptPeriod: 2,
    color: "#7a5010",
  },
  B: {
    name: "Boron",
    Z: 5,
    mass: 10.81,
    group: "Metalloid",
    period: 2,
    ptGroup: 13,
    ptPeriod: 2,
    color: "#2a5a2a",
  },
  C: {
    name: "Carbon",
    Z: 6,
    mass: 12.01,
    group: "Nonmetal",
    period: 2,
    ptGroup: 14,
    ptPeriod: 2,
    color: "#2a5a78",
  },
  N: {
    name: "Nitrogen",
    Z: 7,
    mass: 14.01,
    group: "Nonmetal",
    period: 2,
    ptGroup: 15,
    ptPeriod: 2,
    color: "#2a5a78",
  },
  O: {
    name: "Oxygen",
    Z: 8,
    mass: 16.0,
    group: "Nonmetal",
    period: 2,
    ptGroup: 16,
    ptPeriod: 2,
    color: "#2a5a78",
  },
  F: {
    name: "Fluorine",
    Z: 9,
    mass: 19.0,
    group: "Halogen",
    period: 2,
    ptGroup: 17,
    ptPeriod: 2,
    color: "#6a2050",
  },
  Ne: {
    name: "Neon",
    Z: 10,
    mass: 20.18,
    group: "Noble Gas",
    period: 2,
    ptGroup: 18,
    ptPeriod: 2,
    color: "#3a5a80",
  },
  Na: {
    name: "Sodium",
    Z: 11,
    mass: 22.99,
    group: "Alkali Metal",
    period: 3,
    ptGroup: 1,
    ptPeriod: 3,
    color: "#7a3a10",
  },
  Mg: {
    name: "Magnesium",
    Z: 12,
    mass: 24.31,
    group: "Alkaline Earth",
    period: 3,
    ptGroup: 2,
    ptPeriod: 3,
    color: "#7a5010",
  },
  Al: {
    name: "Aluminum",
    Z: 13,
    mass: 26.98,
    group: "Post-Transition",
    period: 3,
    ptGroup: 13,
    ptPeriod: 3,
    color: "#505050",
  },
  Si: {
    name: "Silicon",
    Z: 14,
    mass: 28.09,
    group: "Metalloid",
    period: 3,
    ptGroup: 14,
    ptPeriod: 3,
    color: "#2a5a2a",
  },
  P: {
    name: "Phosphorus",
    Z: 15,
    mass: 30.97,
    group: "Nonmetal",
    period: 3,
    ptGroup: 15,
    ptPeriod: 3,
    color: "#2a5a78",
  },
  S: {
    name: "Sulfur",
    Z: 16,
    mass: 32.07,
    group: "Nonmetal",
    period: 3,
    ptGroup: 16,
    ptPeriod: 3,
    color: "#2a5a78",
  },
  Cl: {
    name: "Chlorine",
    Z: 17,
    mass: 35.45,
    group: "Halogen",
    period: 3,
    ptGroup: 17,
    ptPeriod: 3,
    color: "#6a2050",
  },
  Ar: {
    name: "Argon",
    Z: 18,
    mass: 39.95,
    group: "Noble Gas",
    period: 3,
    ptGroup: 18,
    ptPeriod: 3,
    color: "#3a5a80",
  },
  K: {
    name: "Potassium",
    Z: 19,
    mass: 39.1,
    group: "Alkali Metal",
    period: 4,
    ptGroup: 1,
    ptPeriod: 4,
    color: "#7a3a10",
  },
  Ca: {
    name: "Calcium",
    Z: 20,
    mass: 40.08,
    group: "Alkaline Earth",
    period: 4,
    ptGroup: 2,
    ptPeriod: 4,
    color: "#7a5010",
  },
  Sc: {
    name: "Scandium",
    Z: 21,
    mass: 44.96,
    group: "Transition Metal",
    period: 4,
    ptGroup: 3,
    ptPeriod: 4,
    color: "#142e58",
  },
  Ti: {
    name: "Titanium",
    Z: 22,
    mass: 47.87,
    group: "Transition Metal",
    period: 4,
    ptGroup: 4,
    ptPeriod: 4,
    color: "#142e58",
  },
  V: {
    name: "Vanadium",
    Z: 23,
    mass: 50.94,
    group: "Transition Metal",
    period: 4,
    ptGroup: 5,
    ptPeriod: 4,
    color: "#142e58",
  },
  Cr: {
    name: "Chromium",
    Z: 24,
    mass: 52.0,
    group: "Transition Metal",
    period: 4,
    ptGroup: 6,
    ptPeriod: 4,
    color: "#142e58",
  },
  Mn: {
    name: "Manganese",
    Z: 25,
    mass: 54.94,
    group: "Transition Metal",
    period: 4,
    ptGroup: 7,
    ptPeriod: 4,
    color: "#142e58",
  },
  Fe: {
    name: "Iron",
    Z: 26,
    mass: 55.85,
    group: "Transition Metal",
    period: 4,
    ptGroup: 8,
    ptPeriod: 4,
    color: "#142e58",
  },
  Co: {
    name: "Cobalt",
    Z: 27,
    mass: 58.93,
    group: "Transition Metal",
    period: 4,
    ptGroup: 9,
    ptPeriod: 4,
    color: "#142e58",
  },
  Ni: {
    name: "Nickel",
    Z: 28,
    mass: 58.69,
    group: "Transition Metal",
    period: 4,
    ptGroup: 10,
    ptPeriod: 4,
    color: "#142e58",
  },
  Cu: {
    name: "Copper",
    Z: 29,
    mass: 63.55,
    group: "Transition Metal",
    period: 4,
    ptGroup: 11,
    ptPeriod: 4,
    color: "#142e58",
  },
  Zn: {
    name: "Zinc",
    Z: 30,
    mass: 65.38,
    group: "Transition Metal",
    period: 4,
    ptGroup: 12,
    ptPeriod: 4,
    color: "#142e58",
  },
  Ga: {
    name: "Gallium",
    Z: 31,
    mass: 69.72,
    group: "Post-Transition",
    period: 4,
    ptGroup: 13,
    ptPeriod: 4,
    color: "#505050",
  },
  Ge: {
    name: "Germanium",
    Z: 32,
    mass: 72.63,
    group: "Metalloid",
    period: 4,
    ptGroup: 14,
    ptPeriod: 4,
    color: "#2a5a2a",
  },
  As: {
    name: "Arsenic",
    Z: 33,
    mass: 74.92,
    group: "Metalloid",
    period: 4,
    ptGroup: 15,
    ptPeriod: 4,
    color: "#2a5a2a",
  },
  Se: {
    name: "Selenium",
    Z: 34,
    mass: 78.97,
    group: "Nonmetal",
    period: 4,
    ptGroup: 16,
    ptPeriod: 4,
    color: "#2a5a78",
  },
  Br: {
    name: "Bromine",
    Z: 35,
    mass: 79.9,
    group: "Halogen",
    period: 4,
    ptGroup: 17,
    ptPeriod: 4,
    color: "#6a2050",
  },
  Kr: {
    name: "Krypton",
    Z: 36,
    mass: 83.8,
    group: "Noble Gas",
    period: 4,
    ptGroup: 18,
    ptPeriod: 4,
    color: "#3a5a80",
  },
  Rb: {
    name: "Rubidium",
    Z: 37,
    mass: 85.47,
    group: "Alkali Metal",
    period: 5,
    ptGroup: 1,
    ptPeriod: 5,
    color: "#7a3a10",
  },
  Sr: {
    name: "Strontium",
    Z: 38,
    mass: 87.62,
    group: "Alkaline Earth",
    period: 5,
    ptGroup: 2,
    ptPeriod: 5,
    color: "#7a5010",
  },
  Y: {
    name: "Yttrium",
    Z: 39,
    mass: 88.91,
    group: "Transition Metal",
    period: 5,
    ptGroup: 3,
    ptPeriod: 5,
    color: "#142e58",
  },
  Zr: {
    name: "Zirconium",
    Z: 40,
    mass: 91.22,
    group: "Transition Metal",
    period: 5,
    ptGroup: 4,
    ptPeriod: 5,
    color: "#142e58",
  },
  Nb: {
    name: "Niobium",
    Z: 41,
    mass: 92.91,
    group: "Transition Metal",
    period: 5,
    ptGroup: 5,
    ptPeriod: 5,
    color: "#142e58",
  },
  Mo: {
    name: "Molybdenum",
    Z: 42,
    mass: 95.95,
    group: "Transition Metal",
    period: 5,
    ptGroup: 6,
    ptPeriod: 5,
    color: "#142e58",
  },
  Tc: {
    name: "Technetium",
    Z: 43,
    mass: 98,
    group: "Transition Metal",
    period: 5,
    ptGroup: 7,
    ptPeriod: 5,
    color: "#142e58",
  },
  Ru: {
    name: "Ruthenium",
    Z: 44,
    mass: 101.07,
    group: "Transition Metal",
    period: 5,
    ptGroup: 8,
    ptPeriod: 5,
    color: "#142e58",
  },
  Rh: {
    name: "Rhodium",
    Z: 45,
    mass: 102.91,
    group: "Transition Metal",
    period: 5,
    ptGroup: 9,
    ptPeriod: 5,
    color: "#142e58",
  },
  Pd: {
    name: "Palladium",
    Z: 46,
    mass: 106.42,
    group: "Transition Metal",
    period: 5,
    ptGroup: 10,
    ptPeriod: 5,
    color: "#142e58",
  },
  Ag: {
    name: "Silver",
    Z: 47,
    mass: 107.87,
    group: "Transition Metal",
    period: 5,
    ptGroup: 11,
    ptPeriod: 5,
    color: "#142e58",
  },
  Cd: {
    name: "Cadmium",
    Z: 48,
    mass: 112.41,
    group: "Transition Metal",
    period: 5,
    ptGroup: 12,
    ptPeriod: 5,
    color: "#142e58",
  },
  In: {
    name: "Indium",
    Z: 49,
    mass: 114.82,
    group: "Post-Transition",
    period: 5,
    ptGroup: 13,
    ptPeriod: 5,
    color: "#505050",
  },
  Sn: {
    name: "Tin",
    Z: 50,
    mass: 118.71,
    group: "Post-Transition",
    period: 5,
    ptGroup: 14,
    ptPeriod: 5,
    color: "#505050",
  },
  Sb: {
    name: "Antimony",
    Z: 51,
    mass: 121.76,
    group: "Metalloid",
    period: 5,
    ptGroup: 15,
    ptPeriod: 5,
    color: "#2a5a2a",
  },
  Te: {
    name: "Tellurium",
    Z: 52,
    mass: 127.6,
    group: "Metalloid",
    period: 5,
    ptGroup: 16,
    ptPeriod: 5,
    color: "#2a5a2a",
  },
  I: {
    name: "Iodine",
    Z: 53,
    mass: 126.9,
    group: "Halogen",
    period: 5,
    ptGroup: 17,
    ptPeriod: 5,
    color: "#6a2050",
  },
  Xe: {
    name: "Xenon",
    Z: 54,
    mass: 131.29,
    group: "Noble Gas",
    period: 5,
    ptGroup: 18,
    ptPeriod: 5,
    color: "#3a5a80",
  },
  Cs: {
    name: "Cesium",
    Z: 55,
    mass: 132.91,
    group: "Alkali Metal",
    period: 6,
    ptGroup: 1,
    ptPeriod: 6,
    color: "#7a3a10",
  },
  Ba: {
    name: "Barium",
    Z: 56,
    mass: 137.33,
    group: "Alkaline Earth",
    period: 6,
    ptGroup: 2,
    ptPeriod: 6,
    color: "#7a5010",
  },
  La: {
    name: "Lanthanum",
    Z: 57,
    mass: 138.91,
    group: "Lanthanide",
    period: 6,
    ptGroup: 3,
    ptPeriod: 6,
    color: "#503070",
  },
  W: {
    name: "Tungsten",
    Z: 74,
    mass: 183.84,
    group: "Transition Metal",
    period: 6,
    ptGroup: 6,
    ptPeriod: 6,
    color: "#142e58",
  },
  Au: {
    name: "Gold",
    Z: 79,
    mass: 196.97,
    group: "Transition Metal",
    period: 6,
    ptGroup: 11,
    ptPeriod: 6,
    color: "#142e58",
  },
  Hg: {
    name: "Mercury",
    Z: 80,
    mass: 200.59,
    group: "Transition Metal",
    period: 6,
    ptGroup: 12,
    ptPeriod: 6,
    color: "#142e58",
  },
  Tl: {
    name: "Thallium",
    Z: 81,
    mass: 204.38,
    group: "Post-Transition",
    period: 6,
    ptGroup: 13,
    ptPeriod: 6,
    color: "#505050",
  },
  Pb: {
    name: "Lead",
    Z: 82,
    mass: 207.2,
    group: "Post-Transition",
    period: 6,
    ptGroup: 14,
    ptPeriod: 6,
    color: "#505050",
  },
  Bi: {
    name: "Bismuth",
    Z: 83,
    mass: 208.98,
    group: "Post-Transition",
    period: 6,
    ptGroup: 15,
    ptPeriod: 6,
    color: "#505050",
  },
  Po: {
    name: "Polonium",
    Z: 84,
    mass: 209,
    group: "Post-Transition",
    period: 6,
    ptGroup: 16,
    ptPeriod: 6,
    color: "#505050",
  },
  At: {
    name: "Astatine",
    Z: 85,
    mass: 210,
    group: "Halogen",
    period: 6,
    ptGroup: 17,
    ptPeriod: 6,
    color: "#6a2050",
  },
  Rn: {
    name: "Radon",
    Z: 86,
    mass: 222,
    group: "Noble Gas",
    period: 6,
    ptGroup: 18,
    ptPeriod: 6,
    color: "#3a5a80",
  },
  Fr: {
    name: "Francium",
    Z: 87,
    mass: 223,
    group: "Alkali Metal",
    period: 7,
    ptGroup: 1,
    ptPeriod: 7,
    color: "#7a3a10",
  },
  Ra: {
    name: "Radium",
    Z: 88,
    mass: 226,
    group: "Alkaline Earth",
    period: 7,
    ptGroup: 2,
    ptPeriod: 7,
    color: "#7a5010",
  },
  Ac: {
    name: "Actinium",
    Z: 89,
    mass: 227,
    group: "Actinide",
    period: 7,
    ptGroup: 3,
    ptPeriod: 7,
    color: "#3a2060",
  },
  U: {
    name: "Uranium",
    Z: 92,
    mass: 238.03,
    group: "Actinide",
    period: 7,
    ptGroup: 6,
    ptPeriod: 7,
    color: "#3a2060",
  },
  Pu: {
    name: "Plutonium",
    Z: 94,
    mass: 244,
    group: "Actinide",
    period: 7,
    ptGroup: 8,
    ptPeriod: 7,
    color: "#3a2060",
  },
};

/* ─── PERIODIC TABLE DATA (group → class) ─── */
const PT_LAYOUT = [
  // [symbol, group_col, period_row]  — 18-column standard layout
  ["H", 1, 1],
  ["He", 18, 1],
  ["Li", 1, 2],
  ["Be", 2, 2],
  ["B", 13, 2],
  ["C", 14, 2],
  ["N", 15, 2],
  ["O", 16, 2],
  ["F", 17, 2],
  ["Ne", 18, 2],
  ["Na", 1, 3],
  ["Mg", 2, 3],
  ["Al", 13, 3],
  ["Si", 14, 3],
  ["P", 15, 3],
  ["S", 16, 3],
  ["Cl", 17, 3],
  ["Ar", 18, 3],
  ["K", 1, 4],
  ["Ca", 2, 4],
  ["Sc", 3, 4],
  ["Ti", 4, 4],
  ["V", 5, 4],
  ["Cr", 6, 4],
  ["Mn", 7, 4],
  ["Fe", 8, 4],
  ["Co", 9, 4],
  ["Ni", 10, 4],
  ["Cu", 11, 4],
  ["Zn", 12, 4],
  ["Ga", 13, 4],
  ["Ge", 14, 4],
  ["As", 15, 4],
  ["Se", 16, 4],
  ["Br", 17, 4],
  ["Kr", 18, 4],
  ["Rb", 1, 5],
  ["Sr", 2, 5],
  ["Y", 3, 5],
  ["Zr", 4, 5],
  ["Nb", 5, 5],
  ["Mo", 6, 5],
  ["Tc", 7, 5],
  ["Ru", 8, 5],
  ["Rh", 9, 5],
  ["Pd", 10, 5],
  ["Ag", 11, 5],
  ["Cd", 12, 5],
  ["In", 13, 5],
  ["Sn", 14, 5],
  ["Sb", 15, 5],
  ["Te", 16, 5],
  ["I", 17, 5],
  ["Xe", 18, 5],
  ["Cs", 1, 6],
  ["Ba", 2, 6],
  ["La", 3, 6],
  ["W", 6, 6],
  ["Au", 11, 6],
  ["Hg", 12, 6],
  ["Tl", 13, 6],
  ["Pb", 14, 6],
  ["Bi", 15, 6],
  ["Po", 16, 6],
  ["At", 17, 6],
  ["Rn", 18, 6],
  ["Fr", 1, 7],
  ["Ra", 2, 7],
  ["Ac", 3, 7],
  ["U", 6, 7],
  ["Pu", 8, 7],
];
const GROUP_CLASS = {
  "Alkali Metal": "pt-alkali",
  "Alkaline Earth": "pt-alkaline",
  "Transition Metal": "pt-transition",
  "Post-Transition": "pt-post",
  Metalloid: "pt-metalloid",
  Nonmetal: "pt-nonmetal",
  Halogen: "pt-halogen",
  "Noble Gas": "pt-noble",
  Lanthanide: "pt-lanthanide",
  Actinide: "pt-actinide",
};
const LEGEND_ITEMS = [
  { cls: "pt-alkali", label: "Alkali" },
  { cls: "pt-alkaline", label: "Alkaline" },
  { cls: "pt-transition", label: "Transition" },
  { cls: "pt-post", label: "Post-Trans" },
  { cls: "pt-metalloid", label: "Metalloid" },
  { cls: "pt-nonmetal", label: "Nonmetal" },
  { cls: "pt-halogen", label: "Halogen" },
  { cls: "pt-noble", label: "Noble Gas" },
  { cls: "pt-actinide", label: "Actinide" },
];
